README.md

A workaround that closes https://github.com/ashvardanian/SimSIMD/issues/46 for now.

Better install instructions for JS

---

javascript/bench.js

The benchmark had some weird `[Object object]' or just blank results for some tests. This is because there were errors not being handled (like MathJS looks at types and does not support TypedArrays).

Deal with errors in bench and fix one

---

.github/workflows/prerelease.yml
.github/workflows/release.yml
.gitignore
README.md
binding.gyp
javascript/bench.mjs
javascript/simsimd.js
javascript/test.mjs
package-lock.json
package.json

I haven't tested the final npm release, so we should coordinate in case something goes back when you run this.
Also, later, we can take out the running on `test-**` branches (though those don't npm publish) (see https://github.com/sroussey/SimSIMD/pull/1).

Change build release process

---

python/lib.c

alert(gpt)
I identified a memory leak issue in the `cdist` function, as well as other metric-like functions, within our codebase. This leak becomes evident in scenarios where these functions are called repeatedly, such as within a `while True` loop. An example to demonstrate the issue is as follows:
```python
while True:
simsimd.cdist(embeddings, query)
```
This code snippet leads to a gradual increase in memory usage over time, indicating a memory leak.
The memory leak stems from the improper handling of numpy arrays, particularly in the context of garbage collection (GC). The issue arises when PyArray_NewFromDescr is used with non-null data. In such cases, the data must remain alive for the entire lifetime of the array. However, it is crucial to allow both numpy and Python's garbage …

Fix for Memory Leak in cdist and Metric-Like Functions

---

golang/simsimd.go

Update the comments for CosineF32, InnerF32, and SqEuclideanF32
functions in the simsimd.go file. The comments incorrectly stated
that these functions compute the similarity between two i8 vectors.
They actually compute the similarity between two f32 vectors. This
change ensures that the comments accurately reflect the
functionality of the code.
The path to the simsimd header file is updated. The header file is
in the 'include' directory.
The math library is now linked in the golang simsimd file. The change was
necessary to resolve undefined references to `logf` and `sqrtf`.
The cosine_f32 function in simsimd.go has been updated to use
simsimd_metric_punned instead of simsimd_neon_f32_cos. This change was
necessary to ensure compatibility across different SIMD architectures.
The previous …

golang: fix some issues in golang bindings

---

include/simsimd/types.h

E.g., USearch depends on this behaviour and expects simsimd to define
`simsimd_f16_t` when passing in SIMSIMD_NATIVE_F16=1 [1]
[1]:https://github.com/unum-cloud/usearch/blob/ce54b814a8a10f4c0c32fee7aad9451231b63f75/include/usearch/index_plugins.hpp#L50
So far this had not caused issues because either `USEARCH_USE_FP16LIB` was set to true or (in benchmarks) `simsimd.h` was included directly, which resulted in this logic in simsimd being evaluated before compilation got to `index_plugins.hpp#L50`.

Define (typedef) simsimd_f16_t even when SIMSIMD_NATIVE_F16 is passed in externally

---

include/simsimd/types.h

USearch depends on this behavior and expects SimSIMD to define `simsimd_f16_t` when passing in SIMSIMD_NATIVE_F16=1 [1].
[1]:
https://github.com/unum-cloud/usearch/blob/ce54b814a8a10f4c0c32fee7aad9451231b63f75/include/usearch/index_plugins.hpp#L50

Fix: Forward SIMSIMD_NATIVE_F16 (#78)

---

Cargo.lock
rust/benches/native.rs

The rust version of cosine_similiraty, which SimSIMD is compared against, was using three separate iterators to calculate intermediate values. 
Combining the iterators into one made the reference speedup by ~200%.
I also went ahead and cleaned up the reference squared_euclidean implementation to follow the same structure (Option instead of assert) and made the iterator more succinct.

Improve Rust bench performance and style

---

Cargo.lock
rust/benches/cosine.rs
rust/benches/native.rs
rust/benches/sqeuclidean.rs

Related to #107 
Optimizes the native implementation in a way that the compiler can actually vectorize the implementations despite the IEE rules.
Although not the simplest, it is more realistic of a 'native' implementation if you are trying to get the maximum speed by going down to intrinsic instructions like AVX.

Optimize Rust impls

---

setup.py

Replace the hardcoded `-lomp` with `-fopenmp` to ensure that the compiler uses the correct OpenMP library.  This is necessary for Clang to correctly link against its own OpenMP implementation, rather than compiling against LLVM OpenMP, then trying to link against libgomp.

Fix linking to the correct OpenMP library

---

CMakeLists.txt

When google benchmark is built with cmake you must define `NDEBUG` when doing a release build or it will build in asserts and complain with
```***WARNING*** Library was built as DEBUG. Timings may be affected.```

Fix: ***WARNING*** Library was built as DEBUG. Timings may be affected.

---

include/simsimd/probability.h

Changed all references for _Float16 to simsimd_f16_t
This has not been tested on sapphire rapids yet, but simsimd_f16_t is _Float16 so this seems innocuous. 
Fixes https://github.com/ashvardanian/SimSIMD/issues/122

Fix: _Float16 warnings

---

Cargo.lock
rust/lib.rs

As we discussed in #124, the new `bf16` type and related functions were forgotten to be exposed on the Rust side, so I just quickly added these! 
I just took a quick look and seems like there are unexposed types and methods in other languages as well:
- JS: `f16`, `bf16`
- Swift: `bf16`
- Go: `f16`, `bf16`
Could you please confirm? If so, would you like to add the missing bindings for these as well?

Expose bf16 to Rust

---

include/simsimd/dot.h

PR for https://github.com/ashvardanian/SimSIMD/issues/167
`simsimd_dot_bf16_neon` has been updated to use the neon dot product intrinsic `vbfdotq_f32` for a 25% speedup.   I have only tested this on AWS t4g and c7g instances.  
Also fixed a couple typos.  simsimd_dot_i8_serial was used instead of _neon, the bf16_neon declarations were missing, and a trailing // was seen on line 526.

Improve: Use the neon dot product intrinsic for `dot_bf16_neon`

---

include/simsimd/simsimd.h

Fixes https://github.com/ashvardanian/SimSIMD/issues/158 by removing the old warning workaround which presumably is no longer needed.   If this was a compiler bug on an older compiler which we still want to support we'll need a different fix as detailed in the issue. 
```
#if defined(__ARM_ARCH)
#define SIMSIMD_DEFAULT_TARGET_ARM __ARM_ARCH
#undef __ARM_ARCH
#endif
```

Fix: `__ARM_ARCH` redefinition warnings

---

c/lib.c
cpp/bench.cxx
include/simsimd/simsimd.h
include/simsimd/spatial.h

The older `bf16` Euclidean Distance implementation had an inefficient implementation for mixed-precision vector subtractions. The new one is very similar, but avoids a couple of serial operations and doubles the throughput:
```c
SIMSIMD_INTERNAL __m512i simsimd_substract_bf16x32_genoa(__m512i a_i16, __m512i b_i16) {
union {
__m512 fvec;
__m512i ivec;
simsimd_f32_t f32[16];
simsimd_u16_t u16[32];
simsimd_bf16_t bf16[32];
} d_odd, d_even, d, a_f32_even, b_f32_even, d_f32_even, a_f32_odd, b_f32_odd, d_f32_odd, a, b;
a.ivec = a_i16;
b.ivec = b_i16;
a_f32_odd.ivec = _mm512_and_si512(a_i16, _mm512_set1_epi32(0xFFFF0000));
a_f32_even.ivec = _mm512_slli_epi32(a_i16, 16);
b_f32_odd.ivec = _mm512_and_si512(b_i16, _mm512_set1_epi32(0xFFFF0000));
b_f32_even.ivec = _mm512_slli_epi32(b_i16, 16); …
```

2x Faster `bf16` Euclidean Distance on AMD Genoa

---

.vscode/settings.json
cpp/bench.cxx
include/simsimd/simsimd.h
include/simsimd/spatial.h
python/test.py

The new `f64` kernels don't benefit much from NEON, given the small 128-bit register size, but instead leverage the `rsqrt` approximations already used in SimSIMD for lower-precision inputs.

Double-precision improvements on Arm

---

.gitignore
python/bench.py
python/bench_perfplot.py

Addresses Issue #193.
@ashvardanian   Here is the start of the PR.  I'm marking it in DRAFT mode because more work is needed on it.
I created a new module `benchmark_perfplot.py` as proof-of-concept of using `perfplot`.  Right now much of using `perfplot` is hard-coded.  For this proof-of-concept, the benchmark compares `np.dot` against `simd.dot` with one dtype.  The plot shows timings for different values of `ndim`.  
As I understand the structure for the original `benchmark.py`, I'm keeping the same structure.  The timing is on how long it takes to process a batch of row vectors, i.e., if the batch is of size `n` and and each row is size `ndim`, then the time reported is the total time it took to process all of the `n` rows of the batch.
Here is a `perfplot` generated for this …

Integrate use of `perfplot` package with benchmark

---

include/simsimd/spatial.h

Accelerated `l2sq_i8_neon` with `vabdq_s8` and unsigned dot-product instructions from 17 GB/s to 33 GB/s.

Improve: 2x Faster L2 on Arm NEON

---

CMakeLists.txt

Without defining the executables as tests automatic tools like "ctest" will not find tests.

Added tests in CMake

---

.vscode/settings.json
CONTRIBUTING.md
README.md
c/lib.c
include/simsimd/elementwise.h
include/simsimd/simsimd.h
include/simsimd/sparse.h
javascript/lib.c
package-lock.json
package.json
python/annotations/__init__.pyi
python/lib.c
scripts/bench.cxx
scripts/bench_vectors.py
scripts/test.py
swift/SimSIMD.swift

Major additions from #218 and cosmetic changes, like #192.

v6: Future-Proofing Dense & Sparse Operations

---

include/simsimd/probability.h
scripts/test.mjs
scripts/test.py

The Jensen Shannom measure implementation in SimSIMD is different from the implementation in scipy. It turns out that a scaling factory of 0.5 was missed and this fix seems to match the example provided in scipy documentation.
Matches the examples provided in the [scipy documentation](https://github.com/scipy/scipy/blob/v1.14.1/scipy/spatial/distance.py#L1186-L1271)

Fix: Refs #207 Fix implementation of Jensen Shannon measure

---

CONTRIBUTING.md
include/simsimd/probability.h
javascript/fallback.ts
package-lock.json
package.json
rust/lib.rs
scripts/test.mjs
scripts/test.py

Fix: Jensen Shannon square roots (#233)

---

javascript/simsimd.ts
rust/lib.rs

Expose the L2 (Euclidean) distance bindings to Rust

feat: #202 Expose L2 distance to Rust

---

rust/lib.rs

Expose the `intersect` method, similar to numpy's `intersect1d` that gives the count of intersection between 2 integer vectors.

feat: #184 Expose intersections rust

---

README.md

As title describes, this commit fixes two typos in the README relating to using this library using Swift. More specifically it changes the `Sift` to `Swift` in the related header so it be can be correctly jumped to when clicking the header link, and changes `you Package.swift` to `your Package.swift`.
Broken Swift link in:
> has [Python](https://github.com/ashvardanian/SimSIMD?tab=readme-ov-file#using-simsimd-in-python), [Rust](https://github.com/ashvardanian/SimSIMD?tab=readme-ov-file#using-simsimd-in-rust), [JS](https://github.com/ashvardanian/SimSIMD?tab=readme-ov-file#using-simsimd-in-javascript), and [Swift](https://github.com/ashvardanian/SimSIMD?tab=readme-ov-file#using-simsimd-in-swift) bindings.
Problem:
> ## Using SimSIMD in Sift
Fix:
> ## Using SimSIMD in Swift
`you …

Fixed 2 typos in README relating to Swift

---

include/simsimd/spatial.h

I am working on benchmarking USearch on different microarchitectures in cloud instances for a research project. 
I noticed a drop in recall in Graviton 4 in all of my datasets when using the `l2sq` metric with `bf16`. Here is an example of the recalls I'm getting with one of my datasets:
|                 Microarchitecture |    Recall |          QPS|
|----------------------------------:|----------:|-------------:|
|                AMD ZEN 4 (r7a.2x) |     >0.99 |     6.54 |
|       **AWS GRAVITON 4 (r8g.2x)** | **0.71** | **3.85** |
|                AMD ZEN 3 (r6a.2x) |     >0.99 |     3.20 |
| INTEL SAPPHIRE RAPIDS Z (r7iz.2x) |     >0.99 |     2.70 |
|    INTEL SAPPHIRE RAPIDS (r7i.2x) |     >0.99 |     2.50 |
I found a small bug (probably a typo) in the code of `l2sq_bf16_sve`. This PR …

Fix: Wrong variable used in `l2sq_bf16_sve`

---

include/simsimd/sparse.h

The sequence for calculating the start of the next iteration has a high latency, so moving it to earlier in the loop improves IPC and thus throughput.
Results from my Zen 4 (~10% better IPC and throughput across the board):
<details><summary>Old</summary>
```
2025-02-14T17:47:24-05:00
Running build_release/simsimd_bench
Run on (16 X 5573 MHz CPU s)
CPU Caches:
L1 Data 32 KiB (x8)
L1 Instruction 32 KiB (x8)
L2 Unified 1024 KiB (x8)
L3 Unified 32768 KiB (x1)
Load Average: 0.74, 0.39, 0.20
***WARNING*** CPU scaling is enabled, the benchmark real time measurements may be noisy and will incur extra overhead.
-------------------------------------------------------------------------------------------------------------------------------------
Benchmark …
```

Improve instruction scheduling for Jaccard distance Icelake

---

include/simsimd/sparse.h

Fixes* `simsimd_spdot_counts_u16_turin` and `simsimd_spdot_weights_u16_turin`.
\*I don't have Zen 5 hardware, so I haven't tested this, but it's at least closer to being correct :).
Draft while I dig into the apparent mis-compilation by clang.
[Godbolt repro of likely compiler bug in context](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1DIApACYAQuYukl9ZATwDKjdAGFUtAK4sGe1wAyeAyYAHI%2BAEaYxCAArKQADqgKhE4MHt6%2BekkpjgJBIeEsUTHxdpgOaUIETMQEGT5%2BXLaY9nkM1bUEBWGR0XG2NXUNWc0KQ93BvcX9sQCUtqhexMjsHOYAzMHI3lgA1CYbbngsLMEExMEAdAiH2CYaAIIPjwQAngmYWFR7XgwpwBC6D2yAQtT2KRYkPQAH0IgAOGEEQ5WJ7vT7fX7/PCAr4gsHECEnaEwvCSVRmJEol4vdFfTA/AFA/HgyEkvCI5EbVGvD70n5/Jl40Gs4knWFeTnUtF8zFC4EKBAkAhEqHi0lcABsVO5tNlDKx8ohSrqqpJXi1Op5dLlOOZ …

Fix: Turin kernels for sparse dot products

---

swift/SimSIMD.swift
swift/Test.swift

Implements https://github.com/ashvardanian/SimSIMD/issues/203
Additionally, guards usage of `Float16` under `#if !arch(x86_64)`, as `Float16` is not available on Intel Macs - [documentation](https://developer.apple.com/documentation/swift/float16#overview), [implementation](https://github.com/swiftlang/swift/blob/53b34604d087c91eb59f22ba28dd892383c61526/stdlib/public/core/FloatingPointTypes.swift.gyb#L71). Without this change I couldn't build SimSIMD Swift package on my Intel Mac.
Ran `swift build && swift test -v`:
```
Apple Swift version 6.0.3 (swiftlang-6.0.3.1.10 clang-1600.0.30.1)
Target: x86_64-apple-macosx10.13
...
Test Suite 'SimSIMDTests' passed at 2025-02-26 09:18:20.429.
Executed 12 tests, with 0 failures (0 unexpected) in 0.006 (0.007) seconds
Test Suite …
```

L2 (Euclidean) distance in Swift 

---

include/simsimd/sparse.h

Re: types
The dot-product intrinsics [_mm256_dpbf16_ps](https://www.intel.com/content/www/us/en/docs/intrinsics-guide/index.html#text=_mm256_dpbf&ig_expand=2668), [_mm256_dpwssd_epi32](https://www.intel.com/content/www/us/en/docs/intrinsics-guide/index.html#ig_expand=2958,5994,4584,5994,2227,5994,2938,5994,6047,3674,4920,2244,691,691,3878,3859,3850,2731,2675,2677,2679,2681,2731,2718&techs=AVX_ALL,AVX_512&text=_mm256*dpwssd*_epi32), and [svbfdot_f32](
https://docsmirror.github.io/A64/2023-06/bfdot_z_zzz.html) each widen the values before multiplying them, so the scalar algorithm should also do that. Also, the macro currently uses the `counter_type`, which is an unsigned int.
---
Re: saturating addition
Same links, none of them perform saturating addition other than the currently used …

Fix: Types in sparse dot-products generic macro
